spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customersdb
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          validation:
            auto: none
