spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          validation:
            auto: none
