spring:
    application:
        name: nvntry
    datasource:
        password: 12345
        url: jdbc:mysql://localhost:3306/productsdb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

